from __future__ import annotations

from datetime import date

from app.crud.hr_staff import create_staff
from app.db.session import SessionLocal
from app.schemas.hr_staff import HRStaffCreate


SAMPLE_ROWS: list[dict] = [
    {
        "full_name": "Amit Sharma",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1990-04-12"),
        "designation": "Staff Nurse",
        "cadre": "Nursing",
        "employment_type": "Regular",
        "phone": "9876543210",
        "email": "amit.sharma@gmail.com",
        "facility_name": "DH-Namsai",
        "facility_type": "District Hospital",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "DH-Namsai",
        "date_of_joining": date.fromisoformat("2018-06-15"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Rina Das",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1993-08-22"),
        "designation": "ANM",
        "cadre": "Nursing",
        "employment_type": "Contractual",
        "phone": "9123456780",
        "email": "rina.das@gmail.com",
        "facility_name": "ANM School",
        "facility_type": "Training School",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "ANM School",
        "date_of_joining": date.fromisoformat("2019-02-11"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Sanjay Borah",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1988-01-18"),
        "designation": "Lab Technician",
        "cadre": "Technical",
        "employment_type": "Regular",
        "phone": "9345678123",
        "email": "sanjay.borah@gmail.com",
        "facility_name": "CHC Mahadevpur",
        "facility_type": "CHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "CHC Mahadevpur",
        "date_of_joining": date.fromisoformat("2017-09-10"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Meena Saikia",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1995-12-05"),
        "designation": "Pharmacist",
        "cadre": "Pharmacy",
        "employment_type": "Contractual",
        "phone": "9234567812",
        "email": "meena.saikia@gmail.com",
        "facility_name": "CHC Chowkam",
        "facility_type": "CHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "CHC Chowkam",
        "date_of_joining": date.fromisoformat("2020-01-08"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Kiran Mishra",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1987-06-30"),
        "designation": "Medical Officer",
        "cadre": "Medical",
        "employment_type": "Regular",
        "phone": "9456781234",
        "email": "kiran.mishra@gmail.com",
        "facility_name": "PHC Lathao",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Lathao",
        "date_of_joining": date.fromisoformat("2016-03-21"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Tina Yadav",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1992-03-15"),
        "designation": "Staff Nurse",
        "cadre": "Nursing",
        "employment_type": "Regular",
        "phone": "9567812345",
        "email": "tina.yadav@gmail.com",
        "facility_name": "PHC Piyong",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Piyong",
        "date_of_joining": date.fromisoformat("2018-11-09"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Ajay Singh",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1991-09-19"),
        "designation": "Data Entry Operator",
        "cadre": "Admin",
        "employment_type": "Contractual",
        "phone": "9678123456",
        "email": "ajay.singh@gmail.com",
        "facility_name": "PHC New Mohong",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC New Mohong",
        "date_of_joining": date.fromisoformat("2021-04-12"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Neha Tamang",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1994-05-11"),
        "designation": "ANM",
        "cadre": "Nursing",
        "employment_type": "Regular",
        "phone": "9781234567",
        "email": "neha.tamang@gmail.com",
        "facility_name": "PHC Emphum",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Emphum",
        "date_of_joining": date.fromisoformat("2019-07-17"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Rahul Debnath",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1989-10-28"),
        "designation": "Pharmacist",
        "cadre": "Pharmacy",
        "employment_type": "Regular",
        "phone": "9892345671",
        "email": "rahul.debnath@gmail.com",
        "facility_name": "DH-Namsai",
        "facility_type": "District Hospital",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "DH-Namsai",
        "date_of_joining": date.fromisoformat("2015-12-14"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Pooja Kalita",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1996-02-08"),
        "designation": "Staff Nurse",
        "cadre": "Nursing",
        "employment_type": "Contractual",
        "phone": "9912345678",
        "email": "pooja.kalita@gmail.com",
        "facility_name": "CHC Mahadevpur",
        "facility_type": "CHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "CHC Mahadevpur",
        "date_of_joining": date.fromisoformat("2022-01-05"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Arun Sharma",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1986-07-14"),
        "designation": "Medical Officer",
        "cadre": "Medical",
        "employment_type": "Regular",
        "phone": "9823456712",
        "email": "arun.sharma@gmail.com",
        "facility_name": "CHC Chowkam",
        "facility_type": "CHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "CHC Chowkam",
        "date_of_joining": date.fromisoformat("2014-08-20"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Sunita Das",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1990-11-03"),
        "designation": "Lab Technician",
        "cadre": "Technical",
        "employment_type": "Regular",
        "phone": "9734567123",
        "email": "sunita.das@gmail.com",
        "facility_name": "PHC Lathao",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Lathao",
        "date_of_joining": date.fromisoformat("2017-10-30"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Vikas Borah",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1993-01-26"),
        "designation": "Pharmacist",
        "cadre": "Pharmacy",
        "employment_type": "Contractual",
        "phone": "9645671234",
        "email": "vikas.borah@gmail.com",
        "facility_name": "PHC Piyong",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Piyong",
        "date_of_joining": date.fromisoformat("2020-09-13"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Nikita Saikia",
        "gender": "Female",
        "date_of_birth": date.fromisoformat("1995-06-18"),
        "designation": "ANM",
        "cadre": "Nursing",
        "employment_type": "Regular",
        "phone": "9556712345",
        "email": "nikita.saikia@gmail.com",
        "facility_name": "PHC New Mohong",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC New Mohong",
        "date_of_joining": date.fromisoformat("2019-05-06"),
        "remarks": "Generated sample entry",
    },
    {
        "full_name": "Deepak Mishra",
        "gender": "Male",
        "date_of_birth": date.fromisoformat("1988-04-01"),
        "designation": "Staff Nurse",
        "cadre": "Nursing",
        "employment_type": "Regular",
        "phone": "9467123456",
        "email": "deepak.mishra@gmail.com",
        "facility_name": "PHC Emphum",
        "facility_type": "PHC",
        "district": "Namsai",
        "block": "Namsai Block",
        "posting_place": "PHC Emphum",
        "date_of_joining": date.fromisoformat("2016-11-18"),
        "remarks": "Generated sample entry",
    },
]


def main() -> None:
    db = SessionLocal()
    created = 0
    skipped = 0
    try:
        # Avoid duplicates if run multiple times.
        from sqlalchemy import select
        from app.models.hr_staff import HRStaff

        for row in SAMPLE_ROWS:
            exists = db.execute(
                select(HRStaff.id).where(
                    HRStaff.full_name == row["full_name"],
                    HRStaff.designation == row["designation"],
                    HRStaff.facility_name == row["facility_name"],
                    HRStaff.deleted_at.is_(None),
                )
            ).first()
            if exists:
                skipped += 1
                continue

            payload = HRStaffCreate(**row)
            create_staff(db, payload)
            created += 1

    finally:
        db.close()

    print(f"seed_staff: created={created} skipped={skipped}")


if __name__ == "__main__":
    main()
