from openpyxl import Workbook
import io
from app.api.routes.hr_agent import _parse_spreadsheet

wb = Workbook()
ws = wb.active
ws.title = "HR Staff — All Facilities"
ws.append(["HR Staff — All Facilities"])
ws.append(["Generated by Data Portal"])
ws.append([])
ws.append(["ID", "Full Name", "Designation", "Facility Name", "Block"])
ws.append([1, "John Doe", "Doctor", "Facility A", "Block 1"])
ws.append([2, "Jane Smith", "Nurse", "Facility B", "Block 2"])
ws.append([None, None, None, None, None])

out = io.BytesIO()
wb.save(out)
data = out.getvalue()

parsed = _parse_spreadsheet(data, "export.xlsx")
print("Headers:", parsed["headers"])
for i, r in enumerate(parsed["rows"]):
    print(f"Row {i}:", r)

