import asyncio
from openpyxl import Workbook
import io
from app.api.routes.hr_agent import _parse_spreadsheet
from app.schemas.hr_staff import HRStaffCreate

def test():
    wb = Workbook()
    ws = wb.active
    ws.title = "HR Staff — All Facilities"
    ws.append(["HR Staff — All Facilities"])
    ws.append(["Generated by Data Portal"])
    ws.append([])
    ws.append(["ID", "Full Name", "Designation", "Facility Name", "Block", "District"])
    ws.append([1, "John Doe", "Doctor", "Facility A", "Block 1", "District A"])
    ws.append([2, "Jane Smith", "Nurse", "Facility B", "Block 2", "District B"])
    
    out = io.BytesIO()
    wb.save(out)
    data = out.getvalue()
    
    parsed = _parse_spreadsheet(data, "export.xlsx")
    rows = parsed["rows"]
    
    mapping_dict = {
        "Full Name": "full_name",
        "Designation": "designation",
        "Facility Name": "facility_name",
        "District": "district",
    }
    
    for r in rows:
        payload = {}
        for k, v in r.items():
            target = mapping_dict.get(k) if mapping_dict else None
            if target:
                is_empty = v is None or (isinstance(v, str) and not v.strip())
                if is_empty:
                    if target in ("full_name", "designation", "facility_name", "district"):
                        payload[target] = "Unknown"
                    else:
                        payload[target] = None
                else:
                    payload[target] = v
                    
        print("Payload:", payload)
        try:
            obj = HRStaffCreate.model_validate(payload)
            print("Success:", obj.full_name)
        except Exception as e:
            print("Validation error:", e)

test()
