"""
This is a very small Alembic script template used by the autogenerated
revision files in this repo.
"""
from alembic import op
import sqlalchemy as sa

${imports if imports else ''}

def upgrade():
${upgrades if upgrades else '    pass'}

def downgrade():
${downgrades if downgrades else '    pass'}
