"""
This is a very small Alembic script template used by the autogenerated
revision files in this repo.
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0f7581edb2c5'
down_revision = '0004_create_admin_access_logs'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('document_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_drafts_draft_id'), 'hr_drafts', ['draft_id'], unique=True)
    op.create_index(op.f('ix_hr_drafts_employee_id'), 'hr_drafts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_drafts_id'), 'hr_drafts', ['id'], unique=False)
    op.create_table('hr_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('fathers_name', sa.String(length=255), nullable=True),
    sa.Column('mothers_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('mode_of_service', sa.String(length=255), nullable=True),
    sa.Column('head', sa.String(length=255), nullable=True),
    sa.Column('present_posting_place', sa.String(length=255), nullable=True),
    sa.Column('appointment_order_no', sa.String(length=500), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('present_basic_pay', sa.String(length=100), nullable=True),
    sa.Column('first_macp', sa.Date(), nullable=True),
    sa.Column('second_macp', sa.Date(), nullable=True),
    sa.Column('third_macp', sa.Date(), nullable=True),
    sa.Column('date_of_retirement', sa.Date(), nullable=True),
    sa.Column('present_address', sa.String(length=1000), nullable=True),
    sa.Column('permanent_address', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=2000), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('profile_photo_original_filename', sa.String(length=512), nullable=True),
    sa.Column('profile_photo_stored_filename', sa.String(length=512), nullable=True),
    sa.Column('profile_photo_content_type', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_staff_designation'), 'hr_staff', ['designation'], unique=False)
    op.create_index(op.f('ix_hr_staff_email'), 'hr_staff', ['email'], unique=False)
    op.create_index(op.f('ix_hr_staff_full_name'), 'hr_staff', ['full_name'], unique=False)
    op.create_index(op.f('ix_hr_staff_id'), 'hr_staff', ['id'], unique=False)
    op.create_index(op.f('ix_hr_staff_phone'), 'hr_staff', ['phone'], unique=False)
    op.create_table('hr_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['hr_staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_notifications_id'), 'hr_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_hr_notifications_staff_id'), 'hr_notifications', ['staff_id'], unique=False)
    op.create_index(op.f('ix_hr_notifications_status'), 'hr_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_hr_notifications_type'), 'hr_notifications', ['type'], unique=False)
    op.create_table('hr_staff_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['hr_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_hr_staff_attachments_id'), 'hr_staff_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_hr_staff_attachments_staff_id'), 'hr_staff_attachments', ['staff_id'], unique=False)
    op.create_index(op.f('ix_admin_access_logs_id'), 'admin_access_logs', ['id'], unique=False)
    op.alter_column('auth_invites', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('auth_invites', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_auth_invites_created_by_user_id'), 'auth_invites', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_auth_invites_id'), 'auth_invites', ['id'], unique=False)
    op.create_index(op.f('ix_auth_invites_redeemed_by_user_id'), 'auth_invites', ['redeemed_by_user_id'], unique=False)
    op.create_index(op.f('ix_auth_invites_role'), 'auth_invites', ['role'], unique=False)
    op.create_index(op.f('ix_auth_invites_token_hash'), 'auth_invites', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_invites_token_preview'), 'auth_invites', ['token_preview'], unique=False)
    op.add_column('auth_users', sa.Column('is_online', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('auth_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('auth_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=False)
    op.create_index(op.f('ix_auth_users_full_name'), 'auth_users', ['full_name'], unique=False)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_phone_number'), 'auth_users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_auth_users_role'), 'auth_users', ['role'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=False)
    op.alter_column('hr_field_defs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hr_field_defs', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_hr_field_defs_id'), 'hr_field_defs', ['id'], unique=False)
    op.create_index(op.f('ix_hr_field_defs_name'), 'hr_field_defs', ['name'], unique=True)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_field_defs_name'), table_name='hr_field_defs')
    op.drop_index(op.f('ix_hr_field_defs_id'), table_name='hr_field_defs')
    op.alter_column('hr_field_defs', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('hr_field_defs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_role'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_phone_number'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_full_name'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.alter_column('auth_users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('auth_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('auth_users', 'is_online')
    op.drop_index(op.f('ix_auth_invites_token_preview'), table_name='auth_invites')
    op.drop_index(op.f('ix_auth_invites_token_hash'), table_name='auth_invites')
    op.drop_index(op.f('ix_auth_invites_role'), table_name='auth_invites')
    op.drop_index(op.f('ix_auth_invites_redeemed_by_user_id'), table_name='auth_invites')
    op.drop_index(op.f('ix_auth_invites_id'), table_name='auth_invites')
    op.drop_index(op.f('ix_auth_invites_created_by_user_id'), table_name='auth_invites')
    op.alter_column('auth_invites', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('auth_invites', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_admin_access_logs_id'), table_name='admin_access_logs')
    op.drop_index(op.f('ix_hr_staff_attachments_staff_id'), table_name='hr_staff_attachments')
    op.drop_index(op.f('ix_hr_staff_attachments_id'), table_name='hr_staff_attachments')
    op.drop_table('hr_staff_attachments')
    op.drop_index(op.f('ix_hr_notifications_type'), table_name='hr_notifications')
    op.drop_index(op.f('ix_hr_notifications_status'), table_name='hr_notifications')
    op.drop_index(op.f('ix_hr_notifications_staff_id'), table_name='hr_notifications')
    op.drop_index(op.f('ix_hr_notifications_id'), table_name='hr_notifications')
    op.drop_table('hr_notifications')
    op.drop_index(op.f('ix_hr_staff_phone'), table_name='hr_staff')
    op.drop_index(op.f('ix_hr_staff_id'), table_name='hr_staff')
    op.drop_index(op.f('ix_hr_staff_full_name'), table_name='hr_staff')
    op.drop_index(op.f('ix_hr_staff_email'), table_name='hr_staff')
    op.drop_index(op.f('ix_hr_staff_designation'), table_name='hr_staff')
    op.drop_table('hr_staff')
    op.drop_index(op.f('ix_hr_drafts_id'), table_name='hr_drafts')
    op.drop_index(op.f('ix_hr_drafts_employee_id'), table_name='hr_drafts')
    op.drop_index(op.f('ix_hr_drafts_draft_id'), table_name='hr_drafts')
    op.drop_table('hr_drafts')
    # ### end Alembic commands ###
