"""
This is a very small Alembic script template used by the autogenerated
revision files in this repo.
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '70153c415071'
down_revision = 'c2e01970fdb9'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('hr_staff') as batch_op:
        batch_op.alter_column('aadhaar_number', type_=sa.String(255), existing_type=sa.String(20))
        batch_op.alter_column('pan_number', type_=sa.String(255), existing_type=sa.String(20))

def downgrade():
    with op.batch_alter_table('hr_staff') as batch_op:
        batch_op.alter_column('aadhaar_number', type_=sa.String(20), existing_type=sa.String(255))
        batch_op.alter_column('pan_number', type_=sa.String(20), existing_type=sa.String(255))
