"""
This is a very small Alembic script template used by the autogenerated
revision files in this repo.
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c2e01970fdb9'
down_revision = '0f7581edb2c5'
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    pass
